my_finance/my_finance/urls.py
from django.contrib import admin
from django.urls import path, include

from transactions.views import index # NOQA

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("transactions/", include("transactions.urls")),
    path("auth/", include("user.urls")),

]

my_finance/transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path("", views.transactions, name="index"),
    path("statistics/", views.statistics, name="statistics"),
    path('income/', views.create_income_transaction, name='income'),
    path('expenses/', views.create_expense_transaction, name='expenses'),
    path('delete_income/<int:income_id>/', views.delete_income_transaction, name='delete_income'),
    path('delete_expense/<int:expense_id>/', views.delete_expense_transaction, name='delete_expense'),
    path('filter_income/', views.filter_income_transaction, name='filter_income'),
    path('filter_expense/', views.filter_expense_transaction, name='filter_expense'),
]

my_finance/user/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
]

my_finance/transactions/models.py
from django.db import models
from django.db.models import ForeignKey
from django.utils.timezone import now
from django.conf import settings


class Income(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=now)
    description = models.TextField()
    category = models.TextField()
    user = ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Owner of incomes",
        on_delete=models.CASCADE,
        related_name='incomes',
    )

    def __str__(self):
        return f"Owner: {self.user_id}, Income: {self.amount}, {self.created_at}, {self.description}, {self.category}"
        # return self.description, self.id  # noQA


class Expense(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=now)
    description = models.TextField()
    category = models.TextField()
    user = ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Owner of expenses",
        on_delete=models.CASCADE,
        related_name='expenses',
    )

    def __str__(self):
        return f"Owner: {self.user_id}, Expense: {self.amount}, {self.created_at}, {self.description}, {self.category}"
        # return self.description, self.id  # noQA

my_finance/transactions/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.timezone import now, timedelta
from django.contrib import messages

from .models import Income, Expense


class BadRequestException(Exception):

    def __init__(self, msg):
        self.msg = msg


# Create your views here.
@login_required(login_url='auth:login')
def index(request):
    return redirect("transactions:index")


@login_required(login_url='auth:login')
def transactions(request):
    return render(request, "transactions/transactions.html")


@login_required(login_url='auth:login')
def statistics(request):
    user = request.user
    incomes = Income.objects.filter(user=user).order_by('-created_at')
    expenses = Expense.objects.filter(user=user).order_by('-created_at')
    total_income = sum([income.amount for income in incomes])
    total_expenses = sum([expense.amount for expense in expenses])
    balance = total_income - total_expenses
    context = {
        "incomes": incomes,
        "expenses": expenses,
        "total_income": total_income,
        "total_expenses": total_expenses,
        "balance": balance,
    }
    return render(request, "transactions/statistics.html", context)


@login_required(login_url='auth:login')
def create_income_transaction(request):
    if request.method == 'POST':
        amount = request.POST['amount']
        created_at = request.POST['created']
        description = request.POST['description']
        category = request.POST['category']
        print(amount, created_at, description, category)
        if not amount:
            messages.add_message(request, messages.ERROR, 'Amount is required')
            return render(request, "transactions/transactions.html", {'amount': amount})
        if created_at == '':
            created_at = now()
        new_income = Income(amount=amount, created_at=created_at, description=description, category=category)
        new_income.user_id = request.user.id
        new_income.save()
        return redirect(reverse('transactions:statistics'))
    return render(request, "transactions/transaction.html")


@login_required(login_url='auth:login')
def create_expense_transaction(request):
    if request.method == 'POST':
        amount_exp = request.POST.get('amount_exp')
        date = request.POST.get('created_exp')
        desc = request.POST.get('description_exp')
        category = request.POST.get('category_exp')
        print(amount_exp, date, desc, category)
        if not amount_exp:
            messages.add_message(request, messages.ERROR, 'Amount is required')
            return render(request, "transactions/transactions.html", {'amount_exp': amount_exp})
        if date == '':
            date = now()
        new_expense = Expense(amount=amount_exp, created_at=date, description=desc, category=category)
        new_expense.user_id = request.user.id
        new_expense.save()
        return redirect(reverse('transactions:statistics'))
    return render(request, "transactions/transaction.html")


@login_required(login_url='auth:login')
def delete_income_transaction(request, income_id):
    income = get_object_or_404(Income, pk=income_id, user=request.user)
    income.delete()
    return redirect(reverse('transactions:statistics'))


@login_required(login_url='auth:login')
def delete_expense_transaction(request, expense_id):
    expense = get_object_or_404(Expense, pk=expense_id, user=request.user)
    expense.delete()
    return redirect(reverse('transactions:statistics'))


@login_required(login_url='auth:login')
def filter_income_transaction(request):
    if request.method == 'POST':
        inc_date_from = request.POST.get('inc_date_from')
        inc_date_to = request.POST.get('inc_date_to')
        print(inc_date_from, inc_date_to)
        if inc_date_from == '':
            inc_date_from = now()-timedelta(days=365)
        if inc_date_to == '':
            inc_date_to = now()

        incomes = Income.objects.filter(created_at__range=[inc_date_from, inc_date_to])
        return render(request, "transactions/statistics.html", {'incomes': incomes})
    return render(request, "transactions/statistics.html")


@login_required(login_url='auth:login')
def filter_expense_transaction(request):
    if request.method == 'POST':
        exp_date_from = request.POST.get('exp_date_from')
        exp_date_to = request.POST.get('exp_date_to')
        print(exp_date_from, exp_date_to)
        if exp_date_from == '':
            exp_date_from = now()-timedelta(days=365)
        if exp_date_to == '':
            exp_date_to = now()

        expenses = Expense.objects.filter(created_at__range=[exp_date_from, exp_date_to])
        return render(request, "transactions/statistics.html", {'expenses': expenses})
    return render(request, "transactions/statistics.html")

my_finance/transactions/templates/transactions/statistics.html
{% extends 'base.html' %}
{% block header %}Statistics{% endblock %}
{% block content %}
<div class="w-full lg:w-5/6">
<h1 class="text-2xl font-bold text-center uppercase">Transactions</h1>
<form method="post" action="{% url 'transactions:filter_income' %}">
{% csrf_token %}
    <label for="inc_from_date">From</label>
    <input class="border-2 rounded-lg py-2 px-6"  id="inc_from_date" type="date" name="inc_date_from">
    <label for="inc_to_date">To</label>
    <input class="border-2 rounded-lg py-2 px-6" id="inc_to_date" type="date" name="inc_date_to">
    <button class="border-2 rounded-lg py-2 px-6" type="submit">Filter</button>
</form>
  <div class="bg-white shadow-md rounded my-6 scroll-auto">
    <table class="min-w-max w-full table-auto">
      <thead>
        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
          <th class="py-3 px-6 text-left">Transaction</th>
          <th class="py-3 px-6 text-left">Amount</th>
          <th class="py-3 px-6 text-center">Category</th>
          <th class="py-3 px-6 text-center">Description</th>
          <th class="py-3 px-6 text-center">Date</th>
          <th class="py-3 px-6 text-center">Actions</th>
        </tr>
      </thead>
      <tbody class="text-gray-600 text-sm font-light">
        {% for income in incomes %}
        <tr class="border-b border-gray-200 hover:bg-gray-100">
          <td class="py-3 px-6 text-center">
            <span class="bg-green-300 text-green-900 py-1 px-3 rounded-full text-xs">
                Income
            </span>
          </td>
          <td class="py-3 px-6 text-center whitespace-nowrap">
            <div class="flex items-center">
              <span class="font-medium">{{ income.amount}} UAH</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
              <span>{{ income.category.title }}</span>
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex items-center justify-center">
              <span>{{ income.description}}</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex items-center justify-center">
              <span>{{ income.created_at.date }}</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex item-center justify-center">
              <div
                class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110"
              >
              <form action="{% url 'transactions:delete_income' income.id %}" method="post">
                  {% csrf_token %}
                  <button class="w-full h-full">
                      <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
                  </button>
              </form>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<h2 class="text-2xl font-semibold leading-tight">Total income: {{ total_income }} UAH</h2>
    <form method="post" action="{% url 'transactions:filter_expense' %}">
{% csrf_token %}
    <label for="exp_from_date">From</label>
    <input class="border-2 rounded-lg py-2 px-6"  id="exp_from_date" type="date" name="exp_date_from">
    <label for="exp_to_date">To</label>
    <input class="border-2 rounded-lg py-2 px-6" id="exp_to_date" type="date" name="exp_date_to">
    <button class="border-2 rounded-lg py-2 px-6" type="submit">Filter</button>
</form>
  <div class="bg-white shadow-md rounded my-6 scroll-auto">
    <table class="min-w-max w-full table-auto">
      <thead>
        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
          <th class="py-3 px-6 text-left">Transaction</th>
          <th class="py-3 px-6 text-left">Amount</th>
          <th class="py-3 px-6 text-center">Category</th>
          <th class="py-3 px-6 text-center">Description</th>
          <th class="py-3 px-6 text-center">Date</th>
          <th class="py-3 px-6 text-center">Actions</th>
        </tr>
      </thead>
      <tbody class="text-gray-600 text-sm font-light">
        {% for expense in expenses %}
        <tr class="border-b border-gray-200 hover:bg-gray-100">
          <td class="py-3 px-6 text-center">
            <span class="bg-red-300 text-red-900 py-1 px-3 rounded-full text-xs">
                Expense
            </span>
          </td>
          <td class="py-3 px-6 text-center whitespace-nowrap">
            <div class="flex items-center">
              <span class="font-medium">{{ expense.amount}} UAH</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
{#            <div class="flex items-center">#}
              <span>{{ expense.category.title }}</span>
{#            </div>#}
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex items-center justify-center">
              <span>{{ expense.description}}</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex items-center justify-center">
              <span>{{ expense.created_at.date }}</span>
            </div>
          </td>
          <td class="py-3 px-6 text-center">
            <div class="flex item-center justify-center">
              <div
                class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110"
              >
              <form action="{% url 'transactions:delete_expense' expense.id %}" method="post">
                  {% csrf_token %}
                  <button class="w-full h-full">
                      <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
                  </button>
              </form>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<h2 class="text-2xl font-semibold leading-tight">Total expense: {{ total_expenses }} UAH</h2>
<h2 class="text-2xl font-semibold leading-tight text-right">Balance: {{ balance }} UAH</h2>
</div>
{% endblock %}

my_finance/transactions/templates/transactions/transactions.html
{% extends 'base.html' %}
{% block header %}Transactions{% endblock %}
{% block content %}
<div class="flex justify-around w-full ">
  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-md w-1/2">
   <div class="flex justify-between">
        <h2 class="mb-3 font-bold">INCOMES</h2>
      {% if messages and amount == '' %}
        {% for message in messages %}
            <p style="color:red; text-align: end; font-size: small">{{ message }}</p>
        {% endfor %}
     {% endif %}
   </div>
    <form method="POST" action="{% url 'transactions:income' %}">{% csrf_token %}
      <div class="grid grid-cols-2 gap-4">
        <div class="form-group mb-6">
          <label for="amount" class="text-sm">Amount</label>
          <input
            type="number"
            name="amount"
            class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding
            border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white
            focus:border-blue-600 focus:outline-none"
            id="amount"
            aria-describedby="emailHelp123"
            placeholder="0"
          />
        </div>
        <div class="form-group mb-6">
          <label for="date" class="text-sm">Date</label>
          <input
            type="date"
            class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            id="date"
            aria-describedby="emailHelp124"
            placeholder="Last name"
            name="created"
          />
        </div>
      </div>
      <div class="form-group mb-6">
        <label
          for="desc_income"
          class="form-label inline-block mb-2 text-gray-700"
          >Description</label
        >
        <textarea
          class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none"
          id="desc_income"
          rows="3"
          placeholder="Comment"
          name="description"
        ></textarea>
      </div>
      <div class="form-group mb-6">
        <select
          class="form-select appearance-none block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
          aria-label="Default select example"
          name="category"
        >
          <option value="OTHER" selected>Open this select menu</option>
          <option value="SALARY BONUS">Salary Bonus</option>
          <option value="PRESENT">Present</option>
          <option value="INVESTMENT">Investment</option>
          <option value="RENT">Rent</option>
          <option value="SAVINGS">Savings</option>
          <option value="INTEREST">Interests</option>
          <option value="SALES">Sales</option>
        </select>
      </div>
      <div class="form-group form-check text-center mb-6"></div>
      <button
        type="submit"
        class="w-full px-6 py-2.5 bg-secondary text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150ease-in-out"
      >
        Add Income
      </button>
    </form>
  </div>

  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-md 1/2">
    <div class="flex justify-between">
        <h2 class="mb-3 font-bold">EXPENSES</h2>
      {% if messages and amount_exp == '' %}
        {% for message in messages %}
            <p style="color:red; text-align: end; font-size: small">{{ message }}</p>
        {% endfor %}
     {% endif %}
   </div>
    <form method="POST" action="{% url 'transactions:expenses' %}">
        {% csrf_token %}
      <div class="grid grid-cols-2 gap-4">
        <div class="form-group mb-6">
          <label for="amount_exp" class="text-sm">Amount</label>
          <input
            type="number"
            class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            id="amount_exp"
            aria-describedby="emailHelp123"
            placeholder="0"
            name="amount_exp"
          />
        </div>
        <div class="form-group mb-6">
          <label for="date_exp" class="text-sm">Date</label>
          <input
            type="date"
            class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            id="date_exp"
            aria-describedby="emailHelp124"
            placeholder="Last name"
            name="created_exp"
          />
        </div>
      </div>
      <div class="form-group mb-6">
        <label for="desc_exp" class="form-label inline-block mb-2 text-gray-700"
          >Description</label
        >
        <textarea
          class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none resize-none"
          id="desc_exp"
          rows="3"
          placeholder="Comment"
          name="description_exp"
        ></textarea>
      </div>
      <div class="form-group mb-6">
        <select
          class="form-select appearance-none block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
          aria-label="Default select example"
            name="category_exp"
        >
          <option value="OTHER" selected>Open this select menu</option>
          <option value="FOOD">Food</option>
          <option value="CAR">Car</option>
          <option value="PRESENT">Present</option>
          <option value="CLOTHES">Clothes</option>
          <option value="TRAVEL">Travel</option>
          <option value="ENTERTAINMENT">Entertainment</option>
          <option value="HEALTH">Health</option>
          <option value="HOBBY">Hobby</option>
        </select>
      </div>
      <div class="form-group form-check text-center mb-6"></div>
      <button
        type="submit"
        class="w-full px-6 py-2.5 bg-accent text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150ease-in-out"
      >
        Add Expense
      </button>
    </form>
  </div>
</div>
{% endblock %}